repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config, pyproject.toml]
        files: ^.*\.py$
      - id: ruff-format
        args: [--config, pyproject.toml]
        files: ^.*\.py$
